name: sds-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit
  - pandas
  - numpy
  - requests
  - geopandas
  - shapely
  - pyproj
  - pyogrio
  - folium
  - matplotlib
  - pip
  - pip:
      - pydeck
      - streamlit-folium